version: '3'
services:
  schematic.cloud:
    container_name: schematic.cloud
    ports:
      - "80:3001"
    image: alsacework/schematic.cloud:latest
    volumes:
      - /data:/app/public
    restart: unless-stopped


