name: Deploy websites to COS

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"  # 使用 Node.js 21 版本
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@1.22.19 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build with Nuxt
        run: yarn build

      - name: Generate
        run: yarn generate

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 安装腾讯云依赖
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install coscmd
          python3.11 -m pip install tccli

      - name: 配置腾讯云依赖
        env:
          SECRET_ID: ${{ secrets.TCLOUD_API_ID }}
          SECRET_KEY: ${{ secrets.TCLOUD_API_KEY }}
          BUCKET: schem-1318358151
          REGION: ap-shanghai
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          tccli configure set secretId $SECRET_ID
          tccli configure set secretKey $SECRET_KEY
          tccli configure set region $REGION

      - name: 上传到腾讯云COS并刷新CDN
        run: |
          coscmd upload -rfs --delete ./.output/public/ /
          tccli cdn PurgePathCache --cli-unfold-argument --Paths https://schem.alsace.team/ --FlushType flush
